# Generated by Django 4.1.5 on 2023-01-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_client',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='numbre_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
