# Generated by Django 4.1.5 on 2023-01-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_name_client_order_numbre_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
