# Generated by Django 4.1.5 on 2023-01-20 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='numbre_order',
            new_name='number_order',
        ),
    ]
