# Generated by Django 4.1.5 on 2023-01-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
