# Generated by Django 4.1.5 on 2023-01-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produc_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produc',
            old_name='categiry',
            new_name='category',
        ),
    ]
