# Generated by Django 4.1.5 on 2023-01-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_categiry_produc_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produc',
            new_name='Product',
        ),
    ]
